jailhouse_cell_desc:
  - signature: JAILHOUSE_CELL_DESC_SIGNATURE
  - revision: 3
  - name: apic-demo

cpus:
  - 0x8

memory_regions:
  -
    - phys_start: 0x3f000000
    - virt_start: 0
    - size: 0x00100000
    - flags: 0x47
  -
    - phys_start: 0
    - virt_start: 0x00100000
    - size: 0x00001000
    - flags: 0x23

cache_regions:
  -
    - start: 0
    - size: 2
    - type: 0x3

pio_bitmap:
  size: 0x2000
  default_value: 0xff
  holes:
    -
      begin: 127
      end: 127
      value: 0
    -
      begin: 7170
      end: 7170
      value: 0
